name: 📝 文档反馈
description: 报告问题或提出建议
title: "[反馈]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的反馈！请简要描述您发现的问题或改进建议。
        
  - type: input
    id: page
    attributes:
      label: 相关页面
      description: 请提供相关的文档页面链接（如适用）
      placeholder: 例如：https://doc.nekro.ai/docs/guide/quickstart
        
  - type: textarea
    id: description
    attributes:
      label: 问题描述/建议
      description: 请描述您发现的问题或您的建议
      placeholder: |
        我发现...
        或者
        我建议...
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 反馈类型
      description: 这是什么类型的反馈？
      options:
        - 文档错误
        - 内容建议
        - 功能建议
        - 使用疑问
        - 其他
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意向
      description: 您是否有意向帮助改进文档？
      options:
        - label: 愿意提交 Pull Request 参与改进 